Console.WriteLine("Enter the first number:");
string number1 = Console.ReadLine();
Console.WriteLine("Enter the second number:");
string number2 = Console.ReadLine();
int num1 = Int32.Parse(number1);
int num2 = Int32.Parse(number2);
int addition = num1 + num2;
Console.WriteLine("Addition: " + addition);
int subtraction = num1 - num2;
Console.WriteLine("Subtraction: " + subtraction);
int multipliation = num1 * num2;
Console.WriteLine("Multipliation: " + multipliation);
double no1 = num1;
double no2 = num2;
double division = no1 / no2;
Console.WriteLine("Division: " + division);